import type {
  HistoryPageData,
  ArticleHistoryItem,
  SnsHistoryItem,
  PoliticianHistoryItem,
  HistoryStats,
} from '@/types/history';

// 기사 히스토리 더미데이터
export const articleHistoryData: ArticleHistoryItem[] = [
  {
    id: '1',
    title: '추경 12조, 7월까지 70% 이상 집행...산불 복구비용 이달 전액 교부',
    thumbnail: '/og-image.png',
    date: '2025년 07월 11일 조회',
    type: 'articles',
    source: '유튜브',
    validity: 'true3',
    validityPercent: 75,
    url: 'https://example.com/article1',
  },
  {
    id: '2',
    title: '정부, 디지털 뉴딜 2.0 발표...AI 인프라 투자 확대',
    thumbnail: '/og-image.png',
    date: '2025년 07월 10일 조회',
    type: 'articles',
    source: '뉴스',
    validity: 'true2',
    validityPercent: 85,
    url: 'https://example.com/article2',
  },
  {
    id: '3',
    title: '한미 정상회담 성과...반도체 협력 강화 합의',
    thumbnail: '/og-image.png',
    date: '2025년 07월 09일 조회',
    type: 'articles',
    source: '유튜브',
    validity: 'true1',
    validityPercent: 95,
    url: 'https://example.com/article3',
  },
  {
    id: '4',
    title: '경제성장률 전망 상향조정...올해 2.8% 예상',
    thumbnail: '/og-image.png',
    date: '2025년 07월 08일 조회',
    type: 'articles',
    source: '뉴스',
    validity: 'true4',
    validityPercent: 65,
    url: 'https://example.com/article4',
  },
  {
    id: '5',
    title: '부동산 정책 변화...전세보증금 상한제 검토',
    thumbnail: '/og-image.png',
    date: '2025년 07월 07일 조회',
    type: 'articles',
    source: '유튜브',
    validity: 'true2',
    validityPercent: 80,
    url: 'https://example.com/article5',
  },
  {
    id: '6',
    title: '환경정책 강화...탄소중립 로드맵 발표',
    thumbnail: '/og-image.png',
    date: '2025년 07월 06일 조회',
    type: 'articles',
    source: '뉴스',
    validity: 'true3',
    validityPercent: 70,
    url: 'https://example.com/article6',
  },
];

// SNS 히스토리 더미데이터
export const snsHistoryData: SnsHistoryItem[] = [
  {
    id: '1',
    title: '정치이야기관련어쩌고...',
    politicianName: '이국민',
    politicianParty: '더불어야잘산당',
    politicianImage: '/people/true1.png',
    snsType: 'x',
    post: '정치이야기관련어쩌고...',
    date: '2025년 07월 11일 조회',
    type: 'sns',
    validity: 'true3',
    validityPercent: 75,
    url: 'https://x.com/example1',
  },
  {
    id: '2',
    title: '정치이야기관련어쩌고...',
    politicianName: '이평등',
    politicianParty: '더불어야잘산당',
    politicianImage: '/people/true2.png',
    snsType: 'facebook',
    post: '정치이야기관련어쩌고...',
    date: '2025년 07월 10일 조회',
    type: 'sns',
    validity: 'true2',
    validityPercent: 85,
    url: 'https://facebook.com/example2',
  },
  {
    id: '3',
    title: '정치이야기관련어쩌고...',
    politicianName: '김차별',
    politicianParty: '더불어야잘산당',
    politicianImage: '/people/true3.png',
    snsType: 'youtube',
    post: '정치이야기관련어쩌고...',
    date: '2025년 07월 09일 조회',
    type: 'sns',
    validity: 'true4',
    validityPercent: 65,
    url: 'https://youtube.com/example3',
  },
  {
    id: '4',
    title: '정치이야기관련어쩌고...',
    politicianName: '김무상',
    politicianParty: '더불어야잘산당',
    politicianImage: '/people/true4.png',
    snsType: 'facebook',
    post: '정치이야기관련어쩌고...',
    date: '2025년 07월 08일 조회',
    type: 'sns',
    validity: 'true1',
    validityPercent: 95,
    url: 'https://facebook.com/example4',
  },
  {
    id: '5',
    title: '정치이야기관련어쩌고...',
    politicianName: '박민주',
    politicianParty: '더불어야잘산당',
    politicianImage: '/people/true5.png',
    snsType: 'x',
    post: '정치이야기관련어쩌고...',
    date: '2025년 07월 07일 조회',
    type: 'sns',
    validity: 'true2',
    validityPercent: 80,
    url: 'https://x.com/example5',
  },
  {
    id: '6',
    title: '정치이야기관련어쩌고...',
    politicianName: '최공정',
    politicianParty: '더불어야잘산당',
    politicianImage: '/people/true1.png',
    snsType: 'youtube',
    post: '정치이야기관련어쩌고...',
    date: '2025년 07월 06일 조회',
    type: 'sns',
    validity: 'true3',
    validityPercent: 70,
    url: 'https://youtube.com/example6',
  },
];

// 정치인 히스토리 더미데이터
export const politicianHistoryData: PoliticianHistoryItem[] = [
  {
    id: '1',
    title: '김국민',
    politicianName: '김국민',
    politicianParty: '민주민주당',
    politicianImage: '/people/true1.png',
    trustScore: 85,
    date: '2025년 07월 11일 조회',
    type: 'politicians',
    validity: 'true2',
    validityPercent: 85,
  },
  {
    id: '2',
    title: '이민주',
    politicianName: '이민주',
    politicianParty: '민주민주당',
    politicianImage: '/people/true2.png',
    trustScore: 78,
    date: '2025년 07월 10일 조회',
    type: 'politicians',
    validity: 'true3',
    validityPercent: 78,
  },
  {
    id: '3',
    title: '박공정',
    politicianName: '박공정',
    politicianParty: '민주민주당',
    politicianImage: '/people/true3.png',
    trustScore: 92,
    date: '2025년 07월 09일 조회',
    type: 'politicians',
    validity: 'true1',
    validityPercent: 92,
  },
  {
    id: '4',
    title: '최평등',
    politicianName: '최평등',
    politicianParty: '민주민주당',
    politicianImage: '/people/true4.png',
    trustScore: 67,
    date: '2025년 07월 08일 조회',
    type: 'politicians',
    validity: 'true4',
    validityPercent: 67,
  },
  {
    id: '5',
    title: '정자유',
    politicianName: '정자유',
    politicianParty: '민주민주당',
    politicianImage: '/people/true5.png',
    trustScore: 89,
    date: '2025년 07월 07일 조회',
    type: 'politicians',
    validity: 'true2',
    validityPercent: 89,
  },
  {
    id: '6',
    title: '한민주',
    politicianName: '한민주',
    politicianParty: '민주민주당',
    politicianImage: '/people/true1.png',
    trustScore: 73,
    date: '2025년 07월 06일 조회',
    type: 'politicians',
    validity: 'true3',
    validityPercent: 73,
  },
];

// 통계 데이터
export const historyStatsData: HistoryStats = {
  title: 'MY 통계',
  description: '이번 주 홍길동 님은 SNS분석에 관심이 많아요',
  chartData: [
    { label: '기사', value: 3, color: 'var(--primary-light)' },
    { label: 'SNS', value: 5, color: 'var(--primary-normal)' },
    { label: '정치인', value: 2, color: 'var(--gray-strong)' },
  ],
};

// 전체 히스토리 페이지 데이터
export const historyPageData: HistoryPageData = {
  currentTab: 'articles',
  currentPage: 1,
  totalPages: 5,
  items: articleHistoryData,
  stats: historyStatsData,
};
