export type VideoItem = {
  date: any;
  publishedAt: any;
  id: string;
  grade: 'true1' | 'true2' | 'true3' | 'true4' | 'true5';
  gradePercent: string;
  gradeColor: string;
  title: string;
  thumbnail: string;
  link: string;
  channelName: string;
};

export const videoList = [
  {
    id: 'ytn-001',
    grade: 'true1',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title: '[자막뉴스] 지이 보일 풍경 / YTN',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-002',
    grade: 'true2',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title:
      '[자막뉴스] 지금과는 전혀 다른 사회...30년 뒤 한국이 보일 풍경 / YTN',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-003',
    grade: 'true3',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title:
      '[자막뉴스] 지금과는 전혀 다른 사회...30년 뒤 한국이 보일 풍경 / YTN',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-004',
    grade: 'true5',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title:
      '[자막뉴스] 지금과는 전혀 다른 사회...30년 뒤 한국이 보일 풍경 / YTN',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-005',
    grade: 'true4',
    gradePercent: '66%',
    gradeColor: 'bg-green-600',
    title:
      '[자막뉴스] 지금과는 전혀 다른 사회...30년 뒤 한국이 보일 풍경 / YTN',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-006',
    grade: 'true1',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title: '[자막뉴스] 마지막 뉴스...30년 뒤 한국이 보일 풍경 / YYY',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-007',
    grade: 'true1',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title: '[자막뉴스] 마지막 뉴스...30년 뒤 한국이 보일 풍경 / YYY',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-008',
    grade: 'true1',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title: '[자막뉴스] 마지막 뉴스...30년 뒤 한국이 보일 풍경 / YYY',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-009',
    grade: 'true1',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title: '[자막뉴스] 마지막 뉴스...30년 뒤 한국이 보일 풍경 / YYY',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-010',
    grade: 'true1',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title: '[자막뉴스] 마지막 뉴스...30년 뒤 한국이 보일 풍경 / YYY',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-011',
    grade: 'true1',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title: '[자막뉴스] 마지막 뉴스...30년 뒤 한국이 보일 풍경 / YYY',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-012',
    grade: 'true1',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title: '[자막뉴스] 마지막 뉴스...30년 뒤 한국이 보일 풍경 / YYY',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-013',
    grade: 'true1',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title: '[자막뉴스] 마지막 뉴스...30년 뒤 한국이 보일 풍경 / YYY',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-014',
    grade: 'true1',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title: '[자막뉴스] 마지막 뉴스...30년 뒤 한국이 보일 풍경 / YYY',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-015',
    grade: 'true1',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title: '[자막뉴스] 마지막 뉴스...30년 뒤 한국이 보일 풍경 / YYY',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-016',
    grade: 'true1',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title: '[자막뉴스] 마지막 뉴스...30년 뒤 한국이 보일 풍경 / YYY',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-017',
    grade: 'true1',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title: '[자막뉴스] 마지막 뉴스...30년 뒤 한국이 보일 풍경 / YYY',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-018',
    grade: 'true1',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title: '[자막뉴스] 마지막 뉴스...30년 뒤 한국이 보일 풍경 / YYY',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-019',
    grade: 'true1',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title: '[자막뉴스] 마지막 뉴스...30년 뒤 한국이 보일 풍경 / YYY',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-020',
    grade: 'true1',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title: '[자막뉴스] 마지막 뉴스...30년 뒤 한국이 보일 풍경 / YYY',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-021',
    grade: 'true1',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title: '[자막뉴스] 마지막 뉴스...30년 뒤 한국이 보일 풍경 / YYY',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-022',
    grade: 'true1',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title: '[자막뉴스] 마지막 뉴스...30년 뒤 한국이 보일 풍경 / YYY',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-023',
    grade: 'true1',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title: '[자막뉴스] 마지막 뉴스...30년 뒤 한국이 보일 풍경 / YYY',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-024',
    grade: 'true1',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title: '[자막뉴스] 마지막 뉴스...30년 뒤 한국이 보일 풍경 / YYY',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-025',
    grade: 'true1',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title: '[자막뉴스] 마지막 뉴스...30년 뒤 한국이 보일 풍경 / YYY',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
  {
    id: 'ytn-026',
    grade: 'true1',
    gradePercent: '96%',
    gradeColor: 'bg-green-600',
    title: '[자막뉴스] 마지YYY',
    thumbnail: 'https://img.youtube.com/vi/xxx/0.jpg',
    link: 'https://www.naver.com/',
    channelName: 'YTN',
  },
];
